version: '3.8'

services:
  ollama:
    image: ollama/ollama:0.3.12
    ports:
      - "11439:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    container_name: sixgpt3-ollama
    deploy:
      resources:
        limits:
          cpus: '6.0'
  sixgpt3-satori:
    image: sixgpt/miner:latest
    ports:
      - "3015:3000"
    depends_on:
      - ollama
    environment:
      - VANA_PRIVATE_KEY=${VANA_PRIVATE_KEY}
      - VANA_NETWORK=satori
    restart: unless-stopped
    container_name: sixgpt3-miner-satori

  sixgpt3-moksha:
    image: sixgpt/miner:latest
    ports:
      - "3016:3000"
    depends_on:
      - ollama
    environment:
      - VANA_PRIVATE_KEY=${VANA_PRIVATE_KEY}
      - VANA_NETWORK=moksha
    restart: unless-stopped
    container_name: sixgpt3-miner-moksha
    
volumes:
  ollama:
